### ISSUE TITLE
Interactive Graph not working in Jupyter notebook

### ISSUE THREAD

**Issue by mgandaman** [paulbrodersen/netgraph#21]
Hello,

I can generate a directed graph using the code in the readme file, but when it displays in Jupyter notebook it is not interactive. Is there something I need to enable in Jupyter Notebooks to make the image interactive? I do not see any other guidance in your documentation.
Here is my code:

```import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import netgraph

edgls = [(1,2),(2,6),(1,2),(2,6),(2,12),(3,2),(3,9),(3,7),(3,8),(4,15),
         (4,12),(5,16),(5,18),(6,24),(7,25),(8,25),(8,15),(9,15),(9,19),
         (9,12),(10,14),(11,10),(12,13),(13,14),(13,19),(14,10),(15,6),
         (15,10),(16,14),(16,20),(16,22),(17,14),(17,26),(18,17),(19,11),
         (20,6),(21,22),(21,15),(23,6),(25,21),(26,9)]

sdmodel = nx.DiGraph()
sdmodel.add_edges_from(edgls)

plt.figure(figsize=(11,11))
netgraph.draw(sdmodel)

plot_instance = netgraph.InteractiveGraph(sdmodel)
```
Thank you!

**Comment by paulbrodersen** [comment]
Hi, thanks for raising the issue. 

A couple of points. 

1) `netgraph` is purely build on matplotlib so your issue is a compatibility issue between matplotlib and jupyter. 

2) Specifically, for interactive graphs, you need to be running a matplotlib backend that is interactive. IIRC, the default backend for notebooks is non-interactive. Prepending `%matplotlib notebook` to your code activates the `notebook` matplotlib backend, which supports interactivity in notebooks. There are many available backends for matplotlib. You can learn about them [here](https://matplotlib.org/faq/usage_faq.html#what-is-a-backend).  

```python 
%matplotlib notebook

import networkx as nx
import matplotlib.pyplot as plt
import netgraph

...
```

3. Interactive drawing in current versions of matplotlib is currently bugged and hence excruciatingly slow. See this [issue](https://github.com/matplotlib/matplotlib/issues/18470). Also there appear to be [additional issues with firefox](https://github.com/matplotlib/matplotlib/issues/18481#issuecomment-692337027). Depending on what matplotlib version and browser you are using, results may hence be subpar even with the correct backend.

**Comment by paulbrodersen** [comment]
I am closing this issue as it appears unrelated to my code base. If you have a counterexample or any further questions regarding this problem, feel free to re-open.
