### ISSUE TITLE
Plt does not work on Pycharm IDE

### ISSUE THREAD

**Issue by SanJacintoJoe** [paulbrodersen/netgraph#24]
The plots generated by your examples in the readme quickly open and then crash/close. No error message is shown. Thus, I believe it's some sort problem either Pycharm IDE or compatibility issues with the latest version matplotlib.

**Comment by paulbrodersen** [comment]
Can you

1. Provide an example that reproduces the error, 
2. paste the error message (if there is any), and
3. post your matplotlib version?

I don't use PyCharm, so there will be a little bit of back and forth between us, but I am sure that we can work out a solution.

**Comment by SanJacintoJoe** [comment]
Here's the example I used from your readme:
![image](https://user-images.githubusercontent.com/61699075/122446820-1675b900-cf71-11eb-8012-c1421b9f7133.png)

I get a plot of the triangle which is not interactive. After I close the plot, another plot quickly areas and then disappears.

I get a readout of exit(0) in terminal. 

My matplotlib version is 3.4.2, the current version to date. I'm also running python version 3.8

**Comment by paulbrodersen** [comment]
Well, exit(0) suggests that the code runs just fine. I have also tested my code with matplotlib 3.4.2, and that doesn't cause any issues on my machine. 

It is not something silly, such as that PyCharm is using a non-interactive matplotlib backend by default? 

1. What is your backend, and is it an interactive one?

```python
import matplotlib
matplotlib.get_backend()
```

The names of all available interactive backends are stored in this variable:
```
print(matplotlib.rcsetup.interactive_bk)
```

If the backend is not in the list of interactive backends, then you can change the backend using 

```
import matplotlib
matplotlib.use('Qt5Agg') # for example
```


**You need to change the backend before importing pyplot from matplotlib (otherwise it will have no effects).**

2. Do any interactive examples on [this page](https://matplotlib.org/stable/gallery/event_handling/ginput_manual_clabel_sgskip.html) work for you?

**Comment by SanJacintoJoe** [comment]
Thank you for taking time to work with me on this.

1. TkAgg was the backend for matplotlib.pyplot
```
print(plt.get_backend())
print(plt.rcsetup.interactive_bk)

TkAgg
['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo']
```
2. I did try the interactive examples. Which worked for me. 

3. I suspect that there's some trigger that is causing the InteractiveGraph method to prematurely close as the non-interactive plot is created and displayed just fine.

**Comment by SanJacintoJoe** [comment]
Actually, I found it works fine if you remove plt.ion from the code in your example.

**Comment by paulbrodersen** [comment]
Thanks for checking the matplotlib backend that PyCharm is using, and glad that you found a workaround.

> I suspect that there's some trigger that is causing the InteractiveGraph method to prematurely close as the non-interactive plot is created and displayed just fine.

It is not a file, so there is no `close()` method. Since removing `plt.ion()` results in a thread-blocking figure but fixes the issue, it seems that the class instance is garbage collected at the end of the PyCharm execution. If that is indeed the case, then the behaviour of PyCharm differs from other REPLs, where those variables would persist. 

1. How exactly are you running the script?
2. If you are running the code snippet in the PyCharm console (with `plt.ion()`), does the issue persist? Google tells me the shortcut for running stuff in the console is Alt+Shift+E ([link](https://www.jetbrains.com/help/pycharm/using-consoles.html#load-code)).

**Comment by SanJacintoJoe** [comment]
1. I'm running it in the IDE. Shortcut is Shift +F10
2. Interestingly, issue does not persist when code in entered via the console.

**Comment by paulbrodersen** [comment]
Ok, then everything makes sense. With Shift+F10, PyCharm runs a piece of code and then garbage collects all variables. This will include the `InteractiveGraph` instance, so there is nothing listening to the events from the figure. With Alt+Shift+E, the variables are sent to the namespace of the console, and everything that is supposed to persist, does indeed hang around. 

As the issue is strictly a product of the idiosyncrasies of PyCharm (and presumably other IDEs), I will not try to work around the issue in my code (I also don't really now how I could). I will make some changes to the documentation to highlight the issue and suggest the workaround of sending code execution to a console. 

Thanks for testing all of those things out for me. That was supremely helpful. If you don't have any other suggestions, then I will close the issue once I have updated the documentation.

**Comment by paulbrodersen** [comment]
I hope the additional comment in the README prevents anyone from running into this issue. 

In ideal world, I would raise a warning if netgraph is imported or run inside a PyCharm IDE, and there is potentially some way to do this, as PyCharm sets [certain environment variables](https://youtrack.jetbrains.com/issue/PY-4853). However, it seems to be impossible to distinguish code execution by the IDE with Shift+F10 from code execution in the console with Alt+Shift+E. Therefor, the warning would be raised even if the execution was done correctly, which seems disruptive and potentially confusing.

I am closing this issue for now but I would happily open it again if someone else comes up with a better solution.
