### ISSUE TITLE
Community Layout

### ISSUE THREAD

**Issue by tboen1** [paulbrodersen/netgraph#41]
Hi Paul, 

I'm having trouble using the plot community functionality. The graph I'm constructing is a simple stochastic block model with two uneven sized communities. For some reason, I keep getting an error that reads "The list of edges has to be non-empty", even through the graph object `g` has 24 nodes and a variable, but certainly non-zero number of edges. I've tried passing in the Networks graph object as an adjacency matrix, edge list, and others forms but for some reason the `Graph` class isn't recognizing the edges in `g`. Do you have any advice? I've pasted the example below. Essentially the only part of the code that I've changed from the tutorial is the generative graph model (stochastic block model). 

For clarity, `networkx` version is `2.6.3` and `netgraph` version is `4.4.1`

```
from netgraph import Graph

# create a modular graph
partition_sizes = np.asarray([4,20])
probs = np.asarray([[0.0, 0.75], [0.75, 0.0]])
g = nx.stochastic_block_model(sizes, probs, seed=0)

# create a dictionary that maps nodes to the community they belong to
node_to_community = dict()
node = 0
for community_id, size in enumerate(partition_sizes):
    for _ in range(size):
        node_to_community[node] = community_id
        node += 1

community_to_color = {
    0 : 'tab:blue',
    1 : 'tab:orange'
}
node_color = {node: community_to_color[community_id] for node, community_id in node_to_community.items()}

Graph(nx.adjacency_matrix(g).todense(),
      node_color=node_color, node_edge_width=0, edge_alpha=0.1,
      node_layout='community', node_layout_kwargs=dict(node_to_community=node_to_community),
      edge_layout='bundled', edge_layout_kwargs=dict(k=2000),
)

plt.show()
```

**Comment by paulbrodersen** [comment]
Finding a community layout consists of two steps. First, netgraph creates a hypergraph, in which nodes correspond to communities, and each edge between two nodes is the sum of edges (or edge weights) between the two corresponding communities. Netgraph then creates a rough graph layout using this hypergraph, which is then subsequently refined in a second step based on the connectivity within communities. 

Your graph is violating the assumptions of this layout routine, as there are no edges within your communities. When netgraph takes the subgraph of each community, the graph is empty, which is why you get the (admittedly cryptic) `"The list of edges has to be non-empty"` error message.

**Comment by paulbrodersen** [comment]
I have implemented a work-around, and pushed the changes to the `dev` branch. You can install the updated version with:

```shell
pip install git+https://github.com/paulbrodersen/netgraph.git@dev
```

Basically, the layout routine now raises a warning and arranges nodes randomly within a community, if the community is unconnected. Your example now looks like this:

![Figure_1](https://user-images.githubusercontent.com/8046146/167383263-14442279-cb4d-4a5f-b6da-5ddfec7f35b3.png)

**Comment by paulbrodersen** [comment]
I will close the issue for now. Feel free to re-open if this does not work for you.

**Comment by tboen1** [comment]
Hi Paul,

Thanks for getting back to me so quickly and for updating the branch. I
understand the error message now, and the new branch works perfectly.

Thanks so much,
Joseph Boen
