### ISSUE TITLE
Minor documentation issues

### ISSUE THREAD

**Issue by ortega2247** [paulbrodersen/netgraph#69]
1. It would be nice to explicitly say that it is necessary to install networkx, igraph, etc, to be able to create the graphs (I wrongly assumed that some of these packages were requirements during the installation)
2. I tried to use EditableGraph on windows and didn't work. It would be nice to have a note that it is not supported on windows (yet?)

**Comment by paulbrodersen** [comment]
> It would be nice to explicitly say that it is necessary to install networkx, igraph, etc, to be able to create the graphs (I wrongly assumed that some of these packages were requirements during the installation)

Thank you for your suggestion. I will make a corresponding note in the documentation.

> I tried to use EditableGraph on windows and didn't work. It would be nice to have a note that it is not supported on windows (yet?)

I have worked on windows 10 boxes with netgraph, so this would surprise me. Please make sure that you are using an interactive matplotlib backend. Note that jupyter notebooks and google colab notebooks do not support event handling and are hence not interactive. If you are using an IDE like pycharm, make sure to run any interactive code in a shell (Alt+Shift+E in pycharm) as IDEs otherwise also typically don't support event handling. You can find instructions on how to switch backends [here](https://matplotlib.org/stable/users/explain/backends.html).

**Comment by rkurchin** [comment]
Linking to [JOSS review](https://github.com/openjournals/joss-reviews/issues/5372) and dropping into to note that I'm not able to find mention of the requirement of a particular matplotlib backend in the docs, so that would be a useful thing to explicitly include...

**Comment by paulbrodersen** [comment]
Commit [643a5e9](https://github.com/paulbrodersen/netgraph/commit/643a5e95521356e315e2a5ff61232738eb83aba9) (and following) expands the documentation to provide instructions for installing all optional dependencies required to run the examples in the documentation. 

Commit [34e200d](https://github.com/paulbrodersen/netgraph/commit/34e200d011ba7e813000a30b67dde6e0b832b195) expands the documentation to provide guidance for troubleshooting issues with matplotlib's event handling. This includes a link to matplotlib's documentation, where all currently available interactive backends are listed. This should hence address also your additional issue, @rkurchin. 

I hope this addresses both of your comments. If not, feel free to re-open.
