### ISSUE TITLE
Question: support for `add_edge`?

### ISSUE THREAD

**Issue by jamesbraza** [paulbrodersen/netgraph#91]
Do you offer the ability to add an edge to a `Graph` after its construction? I don't see anything in the docs for this.

---

Aside: https://stackoverflow.com/a/61459641 needs updating too I think

**Comment by paulbrodersen** [comment]
The class you are looking for is called [`EditableGraph`](https://netgraph.readthedocs.io/en/latest/graph_classes.html#netgraph.EditableGraph). The class is intended for manual graph creation, which is why you can add edges by double-clicking on nodes (see second animation [here](https://netgraph.readthedocs.io/en/latest/interactivity.html)). However, you can also use the `_add_edge(self, source, target, edge_properties=None)` method directly Depending on your environment and matplotlib parameterisation, you may need to call `graph.fig.canvas.draw()` afterwards to update the figure and show the changes.

**Comment by paulbrodersen** [comment]
> Aside: https://stackoverflow.com/a/61459641 needs updating too I think

Thanks for the heads up. What specifically do you feel should be updated?

**Comment by jamesbraza** [comment]
> > Aside: [stackoverflow.com/a/61459641](https://stackoverflow.com/a/61459641) needs updating too I think
> 
> Thanks for the heads up. What specifically do you feel should be updated?

Oh sorry for not specifying. When you run it, the `netgraph.draw` interface no longer exists:

```none
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 13
     10 G.add_edge('3','4')
     11 G.add_edge('4','3')
---> 13 netgraph.draw(G, node_color='w', edge_color='k', edge_width=2.0, node_labels={str(ii) : str(ii) for ii in range(1,5)})
     14 plt.show()

AttributeError: module 'netgraph' has no attribute 'draw'
```

**Comment by jamesbraza** [comment]
`EditableGraph._add_edge` looks great, I will investigate it! Appreciate the answer, going to close this as resolved 👍

**Comment by paulbrodersen** [comment]
> Oh sorry for not specifying. When you run it, the netgraph.draw interface no longer exists

Good catch, thanks!
